#!/bin/sh

set -eu

[ -d ".git" ]

: "${TRANSLATE_DM:=$HOME/git/translate-dm}"
make -C "$TRANSLATE_DM" translate-dm > /dev/null

for dir in v*; do
	[ -d "$dir" ] || continue
	[ $# -eq 0 ] || case "$*" in
		*${dir}*) ;;
		*) continue ;;
	esac

	printf '%s\n' "$dir"
	hash="$(git log -1 --pretty='format:%H' --grep "^Add ${dir}$")"
	[ -n "$hash" ] || continue

	git checkout "$hash" -- "$dir"
	rm -fv -- "$dir/info"
	"$TRANSLATE_DM/translate-dm" \
		--replace \
		--dm "$dir" \
		--queries "$TRANSLATE_DM/queries/excel.yml" \
		--output "$dir/translate.sed" |
		tee -- "$dir/info"

	ok=true
	[ -s "$dir/translate.sed" ] || ok=false
	rm -f -- "$dir/translate.sed"

	if [ "$ok" = false ]; then
		printf 'E: translation failed at %s\n' "$dir"
		exit 1
	fi

	printf '%s\n' "Updating git index"
	git add -- "$dir/ExcelBinOutput"
	if [ -z "$(git status --porcelain -- "$dir/ExcelBinOutput")" ]; then
		git checkout master -- "$dir/info"
	fi
done
